### PR TITLE
"Completed class assignment by making changes to the assignment_1.ipy…

### PR DESCRIPTION
**Pull request by Rarkness**
…nb file"

## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
Adding code to run and anagram checker for boolean output 
## What did you learn from the changes you have made?
.lower to specify changing to lower case
## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?
not really I'm not that experienced 
## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?
Yes, I missed the statement "if not" but was able to figure it out
## How were these changes tested?
I tested them on a command line in the terminal, it worked there but in the file, it shows output to none. Not sure if it's the notebook formatting.
## A reference to a related issue in your repository (if applicable)
I had to delete the repo after I answered the question, as I couldn't pull it. So I started from scratch.
## Checklist
- [X] I can confirm that my changes are working as intended

### CODE REVIEW

**Comment by pedram-aliniaye-asli** [comment]
You did a good job here!
It looks like you've accidentally defined the anagram_checker function inside itself. This creates a recursive call that will cause an error because the function calls itself indefinitely.

To fix this, you should remove the nested definition of anagram_checker and use the correct implementation.
Please go ahead and do the modifications and then let me know, Thanks!

**Comment by Rarkness** [comment]
> You did a good job here! It looks like you've accidentally defined the anagram_checker function inside itself. This creates a recursive call that will cause an error because the function calls itself indefinitely.
> 
> To fix this, you should remove the nested definition of anagram_checker and use the correct implementation. Please go ahead and do the modifications and then let me know, Thanks!

I believe I fixed my code thank you for your help. Let me know if I was successful :)

**Comment by Rarkness** [comment]
Hi thanks for your encouragement lol I don’t feel comfortable with the
material for the most part. I took another run at solving it please let me
know how I did.

I want to submit assignment 2 now. Can I just stage, commit and pull it in
without making another branch?

Meaning I don’t want to overwrite assignment 1 with this new push.

Regards,
Rick

**Comment by pedram-aliniaye-asli** [comment]
you did a great job here!
The part 1 function, has the correct logic but, it won't work for all examples as it considers the case sensitivity of words. So, please try to make it not case-sensitive.
For assignment 2, you need to make a new branch called `assignment-2` and work on the assignment there.
Please go ahead and do the modifications and then let me know. Thanks!

**Comment by Rarkness** [comment]
I made the change to assignment 1 as requested.

I did make a new branch called assignment-2 and submitted it last night.
See attachment

**Comment by Rarkness** [comment]
Can you please check assignment-1 thanks
 https://github.com/Rarkness/python/pull/4
<https://github.com/Rarkness/python/pull/4>

**Pull request closed without merging**
